//! GBE+ standalone-native gamepad profile writer.
//!
//! The writer targets the exact compact section emitted by `config.cpp`.
//! Device selection remains a runtime SDL index because GBE+ does not persist
//! `joy_id`; callers must resolve that index at launch.

use anyhow::{Result, ensure};
use std::collections::BTreeMap;

pub(crate) const SOURCE_COMMIT: &str = "05a05e931b3993ff3e6316b0d841a1fb4d3ac7a7";

pub(crate) const CONTROLS: [&str; 12] = [
    "a", "b", "x", "y", "start", "select", "left", "right", "up", "down", "l", "r",
];

/// Render the source's colon-separated `[#gbe_joy_controls:...]` section.
/// Values are SDL joystick event encodings: 100+button, 200+axis*2+sign,
/// or 300+hat*4+direction, as generated by the native settings UI.
pub(crate) fn gamepad_controls_ini(bindings: &BTreeMap<String, u32>) -> Result<String> {
    ensure!(
        CONTROLS
            .iter()
            .all(|control| bindings.contains_key(*control)),
        "GBE+ gamepad profile needs every controller control"
    );
    let mut values = Vec::with_capacity(CONTROLS.len());
    for control in CONTROLS {
        let value = bindings[control];
        ensure!(value > 0, "GBE+ gamepad event encoding is invalid");
        values.push(value.to_string());
    }
    Ok(format!("[#gbe_joy_controls:{}]\n", values.join(":")))
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    #[test]
    fn renders_colon_separated_native_section() {
        let values = BTreeMap::from([
            ("a".into(), 100),
            ("b".into(), 101),
            ("x".into(), 102),
            ("y".into(), 103),
            ("start".into(), 107),
            ("select".into(), 106),
            ("left".into(), 200),
            ("right".into(), 201),
            ("up".into(), 202),
            ("down".into(), 203),
            ("l".into(), 204),
            ("r".into(), 205),
        ]);
        let ini = super::gamepad_controls_ini(&values).unwrap();
        assert_eq!(
            ini,
            "[#gbe_joy_controls:100:101:102:103:107:106:200:201:202:203:204:205]\n"
        );
    }
}
