//! WinArcadia/AmiArcadia native controller configuration writer.
//!
//! Pinned source: `warmenhoven/amiarcadia`
//! `8ca27c925833fe0021475155512c7f467924f647`.  The WinArcadia frontend
//! persists its controller selectors and eight fire-button assignments per
//! port as ordinary `key=value` entries in `Configs\\WinArcadia.ini`.
//! DirectInput device order is runtime-owned; this writer deliberately does
//! not serialize a product name or pretend that the first two enumerated
//! devices are stable identities.

use anyhow::{Context, Result, ensure};

pub(crate) const SOURCE_COMMIT: &str = "8ca27c925833fe0021475155512c7f467924f647";
pub(crate) const PROFILE_ID: &str = "amiarcadia:winarcadia-directinput-v1";
pub(crate) const CONTROLLER_FIELDS: [&str; 18] = [
    "controller_left",
    "controller_right",
    "leftbutton_0",
    "leftbutton_1",
    "leftbutton_2",
    "leftbutton_3",
    "leftbutton_4",
    "leftbutton_5",
    "leftbutton_6",
    "leftbutton_7",
    "rightbutton_0",
    "rightbutton_1",
    "rightbutton_2",
    "rightbutton_3",
    "rightbutton_4",
    "rightbutton_5",
    "rightbutton_6",
    "rightbutton_7",
];

/// WinArcadia's source-defined controller selector values (aa.h).
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u8)]
pub(crate) enum ControllerKind {
    None = 0,
    Trackball = 1,
    FirstDirectInputJoystick = 2,
    SecondDirectInputJoystick = 3,
    SecondAnalogJoystick = 4,
    FirstDirectInputPad = 5,
    SecondDirectInputPad = 6,
    FirstAnalogPad = 7,
    SecondAnalogPad = 8,
}

impl ControllerKind {
    fn value(self) -> u8 {
        self as u8
    }
}

/// Replace only the source-defined controller lines in a complete copied INI
/// generated by the same executable. WinArcadia's reader consumes its schema
/// positionally, so a missing field is refused rather than appended in a
/// location the executable would not read. Other serialized fields, ordering,
/// and line endings are retained.
/// `buttons` are WinArcadia's one-based `joyfires[]` selectors (1..=8), not
/// host SDL/DirectInput button indices. The caller must resolve and verify
/// the runtime DirectInput enumeration before launch.
pub(crate) fn patch_config(
    baseline: &[u8],
    left: ControllerKind,
    right: ControllerKind,
    buttons: [[u8; 8]; 2],
) -> Result<String> {
    ensure!(
        baseline.len() <= 4 * 1024 * 1024,
        "AmiArcadia config is too large"
    );
    let original = std::str::from_utf8(baseline).context("AmiArcadia config is not UTF-8")?;
    ensure!(
        !original.contains('\0'),
        "AmiArcadia config contains a NUL byte"
    );
    ensure!(
        original
            .lines()
            .next()
            .is_some_and(|line| line.to_ascii_lowercase().starts_with("version=")),
        "AmiArcadia config is not a complete source-generated baseline"
    );
    for port in buttons {
        for button in port {
            ensure!(
                (1..=8).contains(&button),
                "AmiArcadia fire selector must be 1 through 8"
            );
        }
    }

    let values = [
        left.value().to_string(),
        right.value().to_string(),
        buttons[0][0].to_string(),
        buttons[0][1].to_string(),
        buttons[0][2].to_string(),
        buttons[0][3].to_string(),
        buttons[0][4].to_string(),
        buttons[0][5].to_string(),
        buttons[0][6].to_string(),
        buttons[0][7].to_string(),
        buttons[1][0].to_string(),
        buttons[1][1].to_string(),
        buttons[1][2].to_string(),
        buttons[1][3].to_string(),
        buttons[1][4].to_string(),
        buttons[1][5].to_string(),
        buttons[1][6].to_string(),
        buttons[1][7].to_string(),
    ];
    let newline = if original.contains("\r\n") {
        "\r\n"
    } else {
        "\n"
    };
    let mut output = String::with_capacity(original.len() + 512);
    let mut seen = [false; CONTROLLER_FIELDS.len()];

    for line in original.split_inclusive('\n') {
        let (content, ending) = line.strip_suffix('\n').map_or((line, ""), |line| {
            line.strip_suffix('\r')
                .map_or((line, "\n"), |line| (line, "\r\n"))
        });
        if let Some((key, _)) = content.split_once('=') {
            if let Some(index) = CONTROLLER_FIELDS
                .iter()
                .position(|candidate| candidate.eq_ignore_ascii_case(key.trim()))
            {
                ensure!(
                    !seen[index],
                    "AmiArcadia config contains duplicate {key} entry"
                );
                output.push_str(CONTROLLER_FIELDS[index]);
                output.push('=');
                output.push_str(&values[index]);
                output.push_str(if ending.is_empty() { newline } else { ending });
                seen[index] = true;
                continue;
            }
        }
        output.push_str(line);
    }

    ensure!(
        seen.iter().all(|value| *value),
        "AmiArcadia config is missing a positional controller field"
    );
    Ok(output)
}

#[cfg(test)]
mod tests {
    use super::*;

    const DEFAULT_BUTTONS: [[u8; 8]; 2] = [[1, 2, 3, 4, 5, 6, 7, 8], [8, 7, 6, 5, 4, 3, 2, 1]];

    fn baseline(newline: &str) -> String {
        let mut text = format!("version=WinArcadia{newline}before=keep{newline}");
        for field in CONTROLLER_FIELDS {
            text.push_str(&format!("{field}=1{newline}"));
        }
        text.push_str(&format!("after=keep{newline}"));
        text
    }

    #[test]
    fn patches_selectors_and_button_assignments_without_losing_unknown_ini() {
        let input = baseline("\r\n");
        let result = patch_config(
            input.as_bytes(),
            ControllerKind::FirstDirectInputJoystick,
            ControllerKind::SecondDirectInputPad,
            DEFAULT_BUTTONS,
        )
        .unwrap();
        assert!(result.contains("before=keep\r\n"));
        assert!(result.contains("controller_left=2\r\n"));
        assert!(result.contains("controller_right=6\r\n"));
        assert!(result.contains("leftbutton_0=1\r\n"));
        assert!(result.contains("rightbutton_7=1\r\n"));
        assert!(result.contains("after=keep\r\n"));
    }

    #[test]
    fn rejects_non_source_fire_selector() {
        let mut buttons = DEFAULT_BUTTONS;
        buttons[0][0] = 0;
        assert!(
            patch_config(
                baseline("\n").as_bytes(),
                ControllerKind::None,
                ControllerKind::None,
                buttons
            )
            .is_err()
        );
        assert!(
            patch_config(
                b"version=WinArcadia\ncontroller_left=0\n",
                ControllerKind::None,
                ControllerKind::None,
                DEFAULT_BUTTONS
            )
            .is_err()
        );
    }
}
