[package]
name = "lunchbox-app"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
build = "build.rs"

[dependencies]
anyhow.workspace = true
cxx.workspace = true
cxx-qt.workspace = true
cxx-qt-lib.workspace = true
directories.workspace = true
lava_torrent.workspace = true
rusqlite.workspace = true
ureq.workspace = true

[build-dependencies]
cxx-qt-build.workspace = true

[dev-dependencies]
tempfile = "3.14"

[[bin]]
name = "lunchbox"
path = "src/main.rs"
